import { useEffect, useMemo, useRef } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import type {
  AuditLogEntry,
  BackupInfo,
  Device,
  DeviceHistoryEntry,
  DeviceSchedule,
  DiagnosticsSummary,
  DiscoveredDevice,
  Group,
  HealthSummary,
  MessageModalState,
  ToastMessage,
} from "../types/app";
import { createAppTheme } from "../theme";
import { useAppTheme } from "./useAppTheme";
import { getActivePage } from "../utils/app";
import { useAppShellState } from "./useAppShellState";
import { useAppDialogs } from "./useAppDialogs";
import { useAuditData } from "./useAuditData";
import { useSystemData } from "./useSystemData";
import { useRealtimeDeviceSync } from "./useRealtimeDeviceSync";
import { useDeviceData } from "./useDeviceData";
import { useAppContainerDeviceHooks } from "./useAppContainerDeviceHooks";
import PageFallback from "../components/PageFallback";
import { formatPowerText, formatStatusText } from "../utils/device";
import { getActionLabel, getAvailableActionsForDevice, isCronValid } from "../utils/schedule";

export function useAppContainer() {
  const navigate = useNavigate();
  const location = useLocation();
  const activePage = getActivePage(location.pathname);
  const { theme, toggleTheme } = useAppTheme("dark");

  const baseState = useAppShellState();
  const {
    showModal,
    editingId,
    deviceName,
    deviceIp,
    deviceMac,
    deviceBrand,
    modalGroupId,
    search,
    devices,
    groups,
    groupName,
    deviceHistory,
    selectedDeviceId,
    deviceSchedules,
    scheduleCron,
    scheduleAction,
    scheduleUseTime,
    scheduleTime,
    scheduleTarget,
    scheduleDescription,
    scheduleEnabled,
    scheduleSequence,
    currentStepAction,
    editingScheduleId,
    detailTab,
    groupFilter,
    statusFilter,
    powerFilter,
    activityFilter,
    registrationFrom,
    registrationTo,
    backendUrl,
    schedulerOn,
    statusMessage,
    toastMessages,
    auditLogs,
    auditLoading,
    auditDeviceFilter,
    auditGroupFilter,
    auditPage,
    auditPageSize,
    auditTotalCount,
    loading,
    lastRefresh,
    pendingDelete,
    showDeleteConfirm,
    showAssignGroupModal,
    selectedAssignGroupId,
    volumeValue,
    launchTarget,
    messageModal,
    showScheduleBuilder,
    showDiscoveryModal,
    discoveredDevices,
    discoveryLoading,
    selectedDiscoveredDevices,
    healthSummary,
    healthLoading,
    backupList,
    backupLoading,
    selectedBackup,
    diagnostics,
    diagnosticsLoading,
    setShowModal,
    setEditingId,
    setDeviceName,
    setDeviceIp,
    setDeviceMac,
    setDeviceBrand,
    setModalGroupId,
    setSearch,
    setDevices,
    setGroups,
    setGroupName,
    setDeviceHistory,
    setSelectedDeviceId,
    setDeviceSchedules,
    setScheduleCron,
    setScheduleAction,
    setScheduleUseTime,
    setScheduleTime,
    setScheduleTarget,
    setScheduleDescription,
    setScheduleEnabled,
    setScheduleSequence,
    setCurrentStepAction,
    setEditingScheduleId,
    setDetailTab,
    setGroupFilter,
    setStatusFilter,
    setPowerFilter,
    setActivityFilter,
    setRegistrationFrom,
    setRegistrationTo,
    setBackendUrl,
    setSchedulerOn,
    setStatusMessage,
    setToastMessages,
    setAuditLogs,
    setAuditLoading,
    setAuditDeviceFilter,
    setAuditGroupFilter,
    setAuditPage,
    setAuditTotalCount,
    setLoading,
    setLastRefresh,
    setPendingDelete,
    setShowDeleteConfirm,
    setShowAssignGroupModal,
    setSelectedAssignGroupId,
    setVolumeValue,
    setLaunchTarget,
    setMessageModal,
    setShowScheduleBuilder,
    setShowDiscoveryModal,
    setDiscoveredDevices,
    setDiscoveryLoading,
    setSelectedDiscoveredDevices,
    setHealthSummary,
    setHealthLoading,
    setBackupList,
    setBackupLoading,
    setSelectedBackup,
    setDiagnostics,
    setDiagnosticsLoading,
  } = baseState;

  const { removeToast, showToast, showMessage, showConfirm, closeMessageModal } = useAppDialogs({
    setToastMessages,
    setMessageModal,
    setStatusMessage,
  });

  const { loadAuditLogs } = useAuditData({
    baseUrl: backendUrl.replace(/\/$/, ""),
    auditPage,
    auditPageSize,
    setAuditLogs,
    setAuditTotalCount,
    setAuditLoading,
    setAuditPage,
  });

  const {
    forcedOffIdsRef,
    devicesRef,
    refreshAll,
    loadDevices,
    loadGroups,
    recordDeviceEvent,
    resolvePowerStateWithForcedOff,
    setShowDiscoveryModal: setDiscoveryModalOpen,
    setDiscoveryLoading: setDiscoveryLoadingState,
    setSelectedDiscoveredDevices: setDiscoveredSelection,
    setDiscoveredDevices: setDiscoveredDevicesState,
    setStatusMessage: setCurrentStatusMessage,
  } = useDeviceData({
    baseUrl: backendUrl.replace(/\/$/, ""),
    auditDeviceFilter,
    auditGroupFilter,
    auditPage,
    auditPageSize,
    devices,
    setDevices,
    setGroups,
    setDeviceHistory,
    setLoading,
    setLastRefresh,
    setStatusMessage,
    setDiscoveryLoading,
    setDiscoveredDevices,
    setSelectedDiscoveredDevices,
    setShowDiscoveryModal,
    showToast,
    showMessage,
    loadAuditLogs,
  });

  const {
    loadHealthSummary,
    loadBackups,
    loadDiagnostics,
    handleRunMaintenanceNow,
    handleShowDiagnosticsSnapshot,
    handleDownloadDiagnosticsSnapshot,
    handleCreateBackup,
    handleRestoreBackup,
  } = useSystemData({
    baseUrl: backendUrl.replace(/\/$/, ""),
    activePage,
    diagnostics,
    selectedBackup,
    setHealthSummary,
    setHealthLoading,
    setBackupList,
    setBackupLoading,
    setSelectedBackup,
    setDiagnostics,
    setDiagnosticsLoading,
    refreshAll,
    showToast,
    showMessage,
  });

  useRealtimeDeviceSync({
    baseUrl: backendUrl.replace(/\/$/, ""),
    setDevices,
    devicesRef,
    setLastRefresh,
    setStatusMessage: setCurrentStatusMessage,
    recordDeviceEvent,
    resolvePowerStateWithForcedOff,
  });

  const {
    handlePowerOnAll,
    handlePowerOffAll,
    handlePowerOffDevice,
    handlePowerOnDevice,
    handleRestartDevice,
    handleSendDeviceAction,
    handleStartDiscovery,
    handleAddDiscoveredDevices,
    closeDiscoveryModal,
    handleCreateGroup,
    handleRestartGroup,
    handlePowerOnGroup,
    handlePowerOffGroup,
    openAssignGroupModal,
    assignGroupToSelected,
    handleDeleteSelected,
    handleRestartSelected,
    toggleDevice,
    clearModalFields,
    handleOpenModal,
    handleSave,
    confirmDelete,
    cancelDelete,
    handleViewDevice,
    loadDeviceSchedules,
    clearScheduleForm,
    handleEditSchedule,
    handleDeleteSchedule,
    handleToggleSchedule,
    fetchScheduleLogs,
    handleTriggerSchedule,
    handleSaveScheduleBuilder,
    selectedDevice,
    filteredDevices,
    selectedDeviceHistory,
    recentDeviceEvents,
    groupStatusSummary,
    handleOpenDiscovery,
    handleOpenAuditForDevice,
    handleOpenAuditForGroup,
    handleClearSelection,
    handleMessageConfirm,
  } = useAppContainerDeviceHooks({
    baseUrl: backendUrl.replace(/\/$/, ""),
    devices,
    groups,
    discoveredDevices,
    selectedDiscoveredDevices,
    refreshAll,
    loadGroups,
    recordDeviceEvent,
    showToast,
    showMessage,
    showConfirm,
    setStatusMessage: setCurrentStatusMessage,
    setDevices,
    setDiscoveryLoading: setDiscoveryLoadingState,
    setDiscoveredDevices: setDiscoveredDevicesState,
    setSelectedDiscoveredDevices: setDiscoveredSelection,
    setDiscoveryModalOpen: setDiscoveryModalOpen,
    setShowDiscoveryModal: setShowDiscoveryModal,
    groupName,
    setGroupName,
    selectedAssignGroupId,
    setSelectedAssignGroupId,
    setShowAssignGroupModal,
    forcedOffIdsRef,
    editingId,
    deviceName,
    deviceIp,
    deviceMac,
    deviceBrand,
    modalGroupId,
    selectedDeviceId,
    pendingDelete,
    showModal,
    showDiscoveryModal,
    messageModal,
    setEditingId,
    setDeviceName,
    setDeviceIp,
    setDeviceMac,
    setDeviceBrand,
    setModalGroupId,
    setShowModal,
    setSelectedDeviceId,
    setPendingDelete,
    setShowDeleteConfirm,
    setMessageModal,
    setDetailTab,
    scheduleAction,
    scheduleSequence,
    scheduleDescription,
    scheduleEnabled,
    scheduleTarget,
    setDeviceSchedules,
    setScheduleCron,
    setScheduleAction,
    setScheduleTarget,
    setScheduleDescription,
    setScheduleEnabled,
    setScheduleSequence,
    setScheduleUseTime,
    setScheduleTime,
    setEditingScheduleId,
    navigate,
    loadAuditLogs,
    auditPageSize,
    deviceHistory,
    search,
    groupFilter,
    statusFilter,
    powerFilter,
    activityFilter,
    registrationFrom,
    registrationTo,
    discoveryLoading,
    setAuditDeviceFilter,
    setAuditGroupFilter,
    setAuditPage,
    closeMessageModal,
  });

  useEffect(() => {
    if (activePage !== "settings") return;
    void loadHealthSummary();
    void loadBackups();
    void loadDiagnostics();
  }, [activePage, loadBackups, loadDiagnostics, loadHealthSummary]);

  const muiTheme = createAppTheme(theme);
  const pageFallback = <PageFallback />;

  return {
    activePage,
    theme,
    toggleTheme,
    muiTheme,
    pageFallback,
    appLayoutProps: {
      theme,
      toggleTheme,
      loading,
      refreshAll,
      handlePowerOnAll,
      handlePowerOffAll,
      handleOpenModal,
      lastRefresh,
    },
    pageContentProps: {
      activePage,
      pageFallback,
      dashboardProps: {
        devices,
        groupStatusSummary,
        recentDeviceEvents,
      },
      groupsProps: {
        groupStatusSummary,
        groupName,
        setGroupName,
        handleCreateGroup,
        handleRestartGroup,
        handlePowerOnGroup,
        handlePowerOffGroup,
        handleOpenAuditForGroup,
      },
      auditProps: {
        auditDeviceFilter,
        setAuditDeviceFilter,
        auditGroupFilter,
        setAuditGroupFilter,
        loadAuditLogs,
        auditLoading,
        devices,
        groups,
        auditLogs,
        auditPage,
        setAuditPage,
        auditPageSize,
        auditTotalCount,
      },
      settingsProps: {
        backendUrl,
        setBackendUrl,
        schedulerOn,
        setSchedulerOn,
        loadHealthSummary,
        healthLoading,
        healthSummary,
        handleCreateBackup,
        backupLoading,
        loadBackups,
        backupList,
        selectedBackup,
        setSelectedBackup,
        handleRestoreBackup,
        handleRunMaintenanceNow,
        diagnosticsLoading,
        loadDiagnostics,
        handleShowDiagnosticsSnapshot,
        handleDownloadDiagnosticsSnapshot,
        diagnostics,
        showMessage,
      },
      devicesProps: {
        devices,
        groups,
        search,
        setSearch,
        groupFilter,
        setGroupFilter,
        statusFilter,
        setStatusFilter,
        powerFilter,
        setPowerFilter,
        activityFilter,
        setActivityFilter,
        registrationFrom,
        setRegistrationFrom,
        registrationTo,
        setRegistrationTo,
        selectedDevice,
        handleClearSelection,
        handleRestartSelected,
        handleDeleteSelected,
        openAssignGroupModal,
        loading,
        filteredDevices,
        toggleDevice,
        formatPowerText,
        formatStatusText,
        handleViewDevice,
        setEditingId,
        setDeviceName,
        setDeviceIp,
        setDeviceMac,
        setModalGroupId,
        setShowModal,
        handleOpenAuditForDevice,
        handleRestartDevice,
        setPendingDelete,
        setShowDeleteConfirm,
        showDeleteConfirm,
        cancelDelete,
        confirmDelete,
        showAssignGroupModal,
        setShowAssignGroupModal,
        selectedAssignGroupId,
        setSelectedAssignGroupId,
        assignGroupToSelected,
        messageModal,
        setMessageModal,
        closeMessageModal,
        handleMessageConfirm,
        selectedDeviceHistory,
        volumeValue,
        setVolumeValue: (value: string) => setVolumeValue(value.trim() === "" ? "" : String(Math.min(100, Math.max(0, Math.round(Number(value)))))) ,
        launchTarget,
        setLaunchTarget,
        detailTab,
        setDetailTab,
        getDeviceSchedules: (deviceId: number) => deviceSchedules[deviceId] || [],
        getAvailableActions: getAvailableActionsForDevice,
        getActionLabel,
        handleToggleSchedule,
        fetchScheduleLogs,
        handleTriggerSchedule,
        handleEditSchedule,
        handleDeleteSchedule,
        setShowScheduleBuilder,
        scheduleCron,
        setScheduleCron,
        scheduleUseTime,
        setScheduleUseTime,
        scheduleTime,
        setScheduleTime,
        cronValid: isCronValid(scheduleCron),
        scheduleAction,
        setScheduleAction,
        scheduleTarget,
        setScheduleTarget,
        currentStepAction,
        setCurrentStepAction,
        handlePowerOnDevice,
        handlePowerOffDevice,
        handleSendDeviceAction,
        getAvailableActionsForDevice,
        showMessage,
      },
    },
    globalUIProps: {
      loading,
      statusMessage,
      showModal,
      editingId,
      deviceName,
      deviceIp,
      deviceMac,
      deviceBrand,
      modalGroupId,
      groups,
      onDeviceNameChange: setDeviceName,
      onDeviceIpChange: setDeviceIp,
      onDeviceMacChange: setDeviceMac,
      onDeviceBrandChange: setDeviceBrand,
      onModalGroupIdChange: setModalGroupId,
      onModalClose: () => setShowModal(false),
      onOpenDiscovery: handleOpenDiscovery,
      onSave: handleSave,
      showDiscoveryModal,
      discoveryLoading,
      discoveredDevices,
      selectedDiscoveredDevices,
      onDiscoveryClose: closeDiscoveryModal,
      onRetryDiscovery: handleStartDiscovery,
      onAddDiscoveredDevices: handleAddDiscoveredDevices,
      onSelectionChange: setSelectedDiscoveredDevices,
      showScheduleBuilder,
      onScheduleBuilderClose: () => setShowScheduleBuilder(false),
      onScheduleBuilderSave: handleSaveScheduleBuilder,
      onScheduleCronChange: setScheduleCron,
      scheduleCron,
      scheduleActionLabel: getActionLabel(scheduleAction),
      selectedDeviceName: selectedDevice?.name || "Uređaj",
      toastMessages,
      onRemoveToast: removeToast,
    },
  };
}
